# Generated by Django 2.1.7 on 2019-02-28 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r1_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r2_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r3_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r4_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r5_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r6_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r7_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('r8_points_scored', models.PositiveSmallIntegerField(default=0)),
                ('round_jokered', models.PositiveSmallIntegerField(default=8)),
                ('won_tiebreaker', models.BooleanField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quiz')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
