# Generated by Django 2.1.7 on 2019-06-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='first_place',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='second_place',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='third_place',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quizzes.Quiz'),
        ),
        migrations.AlterField(
            model_name='score',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='teams.Team'),
        ),
    ]
